const mongoose = require("mongoose");

const libraryItemSchema = new mongoose.Schema(
  {
    patientId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Patient",
      default: null,
      index: true,
    },
    uploadedBy: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
    bucket: {
      type: String,
      enum: ["memories", "diary", "fitness", "music"],
      required: true,
      index: true,
    },
    sourceType: {
      type: String,
      enum: [
        "upload_photo",
        "upload_video",
        "camera_photo",
        "camera_video",
        "diary_photo",
        "diary_video",
        "google_photos",
        "google_drive",
        "fitness_seed",
        "music_seed",
        "doctor_fitness",
        "doctor_fitness_override",
        "doctor_fitness_hidden",
        "doctor_music",
        "doctor_music_override",
        "doctor_music_hidden",
      ],
      required: true,
      index: true,
    },
    mediaType: {
      type: String,
      enum: ["image", "video", "youtube", "spotify", "external"],
      required: true,
      index: true,
    },
    title: { type: String, default: "" },
    description: { type: String, default: "" },
    mimeType: { type: String, default: "" },
    sizeBytes: { type: Number, default: 0 },
    storagePath: { type: String, default: "" },
    thumbnailPath: { type: String, default: "" },
    capturedAt: { type: Date, default: null },
    uploadedAt: { type: Date, default: Date.now },
    folderYear: { type: String, default: "" },
    folderMonth: { type: String, default: "" },
    folderDay: { type: String, default: "" },
    folderTime: { type: String, default: "" },
    diaryEntryId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "DiaryEntry",
      default: null,
      index: true,
    },
    pregnancyWeek: { type: Number, default: null },
    pregnancyMonth: { type: Number, default: null },
    trimester: {
      type: String,
      enum: ["first", "second", "third", "all", ""],
      default: "",
      index: true,
    },
    doctorId: { type: String, default: "" },
    category: { type: String, default: "" },
    isDefault: { type: Boolean, default: false },
    youtubeVideoId: { type: String, default: "" },
    defaultYouTubeVideoId: { type: String, default: "" },
    youtubeUrl: { type: String, default: "" },
    spotifyId: { type: String, default: "" },
    defaultSpotifyId: { type: String, default: "" },
    spotifyType: {
      type: String,
      enum: ["", "track", "playlist", "album"],
      default: "",
    },
    spotifyUrl: { type: String, default: "" },
    embedUrl: { type: String, default: "" },
    sourceAuthority: { type: String, default: "" },
    tags: [{ type: String }],
    checksum: { type: String, default: "" },
    isEncrypted: { type: Boolean, default: false },
    encryptionMeta: {
      status: {
        type: String,
        enum: ["not_enabled", "pending", "encrypted"],
        default: "not_enabled",
      },
      keyRef: { type: String, default: "" },
      provider: { type: String, default: "" },
    },
    adminVisibility: {
      type: String,
      enum: ["patient_admin", "admin_only"],
      default: "patient_admin",
    },
    isSyncedFromGoogle: { type: Boolean, default: false },
    googleSourceType: {
      type: String,
      enum: ["", "google_photos", "google_drive"],
      default: "",
    },
    googleSourceId: { type: String, default: "" },
    status: {
      type: String,
      enum: ["active", "deleted"],
      default: "active",
      index: true,
    },
  },
  { timestamps: true }
);

libraryItemSchema.index({
  patientId: 1,
  bucket: 1,
  mediaType: 1,
  sourceType: 1,
  createdAt: -1,
});

module.exports = mongoose.model("LibraryItem", libraryItemSchema);
